receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  redis:
    endpoint: 'redis:6379'
    collection_interval: 10s

processors:
exporters:
  debug:
    verbosity: detailed
  otlp:
      endpoint: openobserve:5081
      headers:
        Authorization: "Basic cm9vdEBleGFtcGxlLmNvbTp6bUkzTTVpb3RVcXdXUXZi"
        organization: default
        stream-name: default
      tls:
        insecure: true
service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug, otlp]
    traces:
      receivers: [otlp]
      exporters: [debug, otlp]
    metrics:
      receivers: [otlp]
      exporters: [debug, otlp]
    metrics/redis:
      receivers: [redis]
      exporters: [debug, otlp]
