receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  redis:
    endpoint: 'redis:6379'
    collection_interval: 10s

processors:
exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug]
    traces:
      receivers: [otlp]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      exporters: [debug]
    metrics/redis:
      receivers: [redis]
      exporters: [debug]
